# Cosa e'mandinga
## Analizando Impute de scikit-learn
por [Lucas Pogorelsky](http://www.twitter.com/lucpogo)

Estábamos con [@federicobayle](http://www.twitter.com/federicobayle) debatiendo acerca de métodos de imputación y nos dimos cuenta que no hay un criterio unificado acerca del valor a utilizar al imputar en testing/dev.

Se usa la medida de training o se recalcula para testing?

Para no tener que tomar una decisión, me fijé qué es lo que hacen en sklearn.

In [2]:
import numpy as np
from sklearn.preprocessing import Imputer

## Axis=0

In [51]:
X_long = np.array([[1,2,3,4,5,np.nan],[10,9,8,7,6,10]]).T
X_long

array([[ 1., 10.],
       [ 2.,  9.],
       [ 3.,  8.],
       [ 4.,  7.],
       [ 5.,  6.],
       [nan, 10.]])

In [52]:
imputar_long = Imputer(strategy='median',axis=0,copy=False)

In [53]:
imputar_long.fit(X_long)

Imputer(axis=0, copy=False, missing_values='NaN', strategy='median',
    verbose=0)

In [54]:
imputar_long.transform(np.array([[10,20,30,40,50,np.nan],[10,9,8,7,6,5]]).T)

array([[10., 10.],
       [20.,  9.],
       [30.,  8.],
       [40.,  7.],
       [50.,  6.],
       [ 3.,  5.]])

Al usar el eje 0 (columnas), utiliza la mediana de los **valores con los que hicimos el fit**

## Axis=1

In [60]:
X_wide = np.array([[1,2,3,4,5,np.nan],[10,9,8,7,6,10]])
X_wide

array([[ 1.,  2.,  3.,  4.,  5., nan],
       [10.,  9.,  8.,  7.,  6., 10.]])

In [61]:
imputar_wide = Imputer(strategy='median',axis=1,copy=False)

In [62]:
imputar_wide.fit(X_wide)

Imputer(axis=1, copy=False, missing_values='NaN', strategy='median',
    verbose=0)

In [63]:
imputar_wide.transform(np.array([[10,20,30,40,50,np.nan],[10,9,8,7,6,5]]))

array([[10., 20., 30., 40., 50., 30.],
       [10.,  9.,  8.,  7.,  6.,  5.]])

Al usar el eje 0 (filas), utiliza la mediana de los **valores a los que le aplicamos el transform**

Eso fue todo, espero que les haya gustado [cortina de Nivel X]